#!/usr/bin/env python
import nearproteins as nerp

import argparse
import logging

from Bio import SeqIO


def parse_args():

    parser = argparse.ArgumentParser()

    parser.add_argument('--input', default='/dev/stdin')
    parser.add_argument('--output', default='/dev/stdout')

    return parser.parse_args()


def main():
    args = parse_args()

    logging.basicConfig(level=logging.INFO,
            filename='/dev/stderr')

    store = nerp.SimilarStringStore()
    logging.info('store: %s' % store)

    logging.info('clearing store')
    store.engine.clean_all_buckets()

    with open(args.input) as handle:
        records = SeqIO.parse(handle, 'fasta')

        for i, record in enumerate(records):
            if i%1000 == 0:
                logging.info('loading protein # %i' % i)
            store.add(record.id, str(record.seq))


if __name__ == '__main__':
    main()
